---
- name: Deploy Canaima NFS server
  hosts: nfs
  remote_user: ansible
  become: true
  tasks:
  - import_role:
      name: nfs_server
      tasks_from: install

- name: Deploy Mesos master nodes
  hosts: canaima_mesos_masters
  remote_user: ansible
  become: true
  tasks:
  - import_role:
      name: mesos
      tasks_from: install_master
      
- name: Send Ansible controller node ssh key to hadoop user
  hosts: localhost
  tasks:
  - name : Send Ansible controller node ssh key to hadoop user
    shell: sshpass -p hadoop ssh-copy-id -i /home/torea/.ssh/id_rsa.pub -o StrictHostKeyChecking=no hadoop@"{{ template_ip }}"

- name: Create mesos-slave1 (hadoop node)
  hosts: canaima_pc1
  remote_user: etudiant
  tasks:
  - include_role:
      name: vm_creation
      tasks_from: install_centos
  vars:
    vm_ip: 192.168.4.172
    vm_name: canaima-mesos-slave1
    vm_memory: 8192
    vm_cpus: 2
    is_hadoop: true

- name: Create mesos-slave2 (hadoop node)
  hosts: canaima_pc2
  remote_user: etudiant
  tasks:
  - include_role:
      name: vm_creation
      tasks_from: install_centos
  vars:
    vm_ip: 192.168.4.173
    vm_name: canaima-mesos-slave2
    vm_memory: 8192
    vm_cpus: 2
    is_hadoop: yes
  
- name: Create mesos-slave3 (hadoop node)
  hosts: canaima_pc3
  remote_user: etudiant
  tasks:
  - include_role:
      name: vm_creation
      tasks_from: install_centos
  vars:
    vm_ip: 192.168.4.174
    vm_name: canaima-mesos-slave3
    vm_memory: 8192
    vm_cpus: 2
    is_hadoop: yes

- name: Deploy mesos-slave on slave nodes (agents)
  hosts: canaima_mesos_slaves
  remote_user: ansible
  become: true
  tasks:
  - import_role:
      name: mesos
      tasks_from: install_slave

  
